apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    example.app.type: echo
  name: example-echo-server
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      example.app.type: echo
  template:
    metadata:
      labels:
        example.app.type: echo
    spec:
      containers:
        - name: echo-server-cnt
          image: jmalloc/echo-server
          ports:
            - containerPort: 8080
